server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.jsx$ {
        add_header Content-Type "application/javascript; charset=utf-8";
    }

    location ~* \.(js|jsx|html|css)$ {
        add_header Cache-Control "public, max-age=86400";
    }

    location = /books.json {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
